Django Project 2/DjangoProject/BariVara/urls.py
from django.contrib import admin
from django.urls import path

from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    path('', views.HomePage, name='HomePage'),
    path('create_advertisements', views.create_advertisements, name='create_advertisements'),
    path('advertisement_edit/<int:id>/', views.advertisement_edit, name='advertisement_edit'),
    path('advertisement_delete/<int:id>/', views.advertisement_delete, name='advertisement_delete'),
    path('advertisement_details/<int:id>/', views.advertisement_details, name='advertisement_details'),
    path('search', views.Search, name='search'),
    path('filter', views.Filter, name='filter'),
    path('your_advertisements',views.your_advertisements, name='your_advertisements'),
    

    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django Project 2/DjangoProject/DjangoProject/urls.py
from django.contrib import admin
from django.urls import path , include
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup/',user_views.signup,name='signup'),
    path('',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('profile/',user_views.profile, name='profile'),
    path('BariVara/', include('BariVara.urls')),
    path('accounts/login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django Project 2/DjangoProject/BariVara/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from PIL import Image

# Create your models here.

# model for creating advertisements
class advertisements(models.Model):
    PLACE=[
        ('mothijheel', 'Mothijheel'),
        ('bonosree', 'Bonosree'),
        ('mirpur', 'Mirpur'),
        ('khilgao', 'Khilgao'),
        ('gulshan', 'Gulshan'),
        ('badda', 'Badda'),
        ('uttora', 'Uttora'),
        ('banani', 'Banani'),
    ]
    place=models.CharField(max_length=30,choices=PLACE)
    address=models.CharField(max_length=50)
    bedroom=models.PositiveSmallIntegerField()
    bathroom=models.PositiveSmallIntegerField()
    rent=models.PositiveIntegerField()
    size=models.PositiveIntegerField()
    date_posted=models.DateTimeField(default=timezone.now)
    owner= models.ForeignKey(User,on_delete=models.CASCADE)
    number=models.PositiveIntegerField(null=True)
    
      
    def get_absolute_url(self):
        return reverse('advertisement_details', kwargs={'id':self.id})

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

# Model for uploading images
class images(models.Model):
    advertisement=models.ForeignKey(advertisements,on_delete=models.CASCADE)
    image=models.ImageField(upload_to='house_pics/',blank=True, null=True)

    def __str__(self):
        return self.advertisement.place + "Image"


# Model for comment section
class Comment(models.Model):
    advertisement=models.ForeignKey(advertisements,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    reply = models.ForeignKey('Comment' , null=True , related_name = "replies" , on_delete = models.CASCADE)
    content=models.TextField(max_length=200)
    timestamp=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{}-{}'.format(self.advertisement.id, str(self.user.username))

    
    

Django Project 2/DjangoProject/BariVara/forms.py
from django import forms
from . import models
from .models import Comment
from django.forms import ModelForm

# Form for creating new advertisement
class advertisementForm(forms.ModelForm):
    class Meta:
        model= models.advertisements
        fields=['place','address','bedroom','bathroom','rent','size','number',]

# Form for editing advertisement
class advertisementEditForm(forms.ModelForm):
    class Meta:
        model= models.advertisements
        fields=['place','address','bedroom','bathroom','rent','size','number',]        

# Form for comment section in particular advertisement
class commentForm(forms.ModelForm):


	content = forms.CharField(label="" , widget = forms.Textarea(attrs={'class': 'form-control' , 'placeholder': 'text goes here' , 'rows':'2' , 'cols': '60'}))

	class Meta:

		model = Comment
		fields = ('content',)

       


     

Django Project 2/DjangoProject/BariVara/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .forms import *
from .models import advertisements,images,Comment
from django.forms import modelformset_factory
from django.contrib import messages
from django.http import HttpResponse,HttpResponseRedirect,Http404
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Function for homepage after login
def HomePage(request):

    advertisement = advertisements.objects.all().order_by('-id')
    paginator = Paginator(advertisement, 6)
    page = request.GET.get('page')
    try:
        advertisement = paginator.page(page)
    except PageNotAnInteger:
        advertisement = paginator.page(1)
    except EmptyPage:
        advertisement = paginator.page(paginator.num_pages)
    context = {
        'advertisement' : advertisement,
    }
    return render(request, 'BariVara/HomePage.html', context)

# Function for creating new advertisement
def create_advertisements(request):
    ImageFormset= modelformset_factory(images,fields=('image',),extra=3)
    if request.method=='POST':
        form=advertisementForm(request.POST)
        formset=ImageFormset(request.POST or None, request.FILES or None)
        if form.is_valid() and formset.is_valid():
            advertisement=form.save(commit=False)
            advertisement.owner=request.user
            advertisement.save()
            for f in formset:
                try:
                    photo=images(advertisement=advertisement,image=f.cleaned_data['image'])
                    photo.save()                   
                except Exception as e:
                    break
            return redirect('HomePage')
            
    else:
        form=advertisementForm()
        formset= ImageFormset(queryset=images.objects.none())
    
    context={
        'form':form,
        'formset':formset,
    }
    return render (request,'BariVara/create_advertisements.html',context)

# Function for editing advertisement
def advertisement_edit(request, id):
    advertisement = get_object_or_404(advertisements, id=id)
    ImageFormset= modelformset_factory(images,fields=('image',),extra=3, max_num=3)
    if advertisement.owner != request.user:
        raise Http404()
    if request.method == "POST":
        form = advertisementEditForm(request.POST or None, instance=advertisement)
        formset=ImageFormset(request.POST or None, request.FILES or None)
        if form.is_valid() and formset.is_valid():
            form.save()
            print(formset.cleaned_data)
            data = images.objects.filter(advertisement=advertisement)
            for index, f in enumerate(formset):
                if f.cleaned_data:
                    if f.cleaned_data['id'] is None:
                        photo=images(advertisement=advertisement,image=f.cleaned_data['image'])
                        photo.save()
                    elif f.cleaned_data['image'] is False:
                        photo = images.objects.get(id=request.POST.get('form-'+str(index)+'-id'))
                        photo.delete()
                    else:
                        photo=images(advertisement=advertisement,image=f.cleaned_data['image'])
                        d = images.objects.get(id=data[index].id)
                        d.image = photo.image
                        d.save()

            return HttpResponseRedirect(advertisement.get_absolute_url())
    else:
        form = advertisementEditForm(instance=advertisement)
        formset = ImageFormset(queryset=images.objects.filter(advertisement=advertisement))
        context = {
            'form': form,
            'advertisement': advertisement,
            'formset':formset,
        }
    return render(request, 'Barivara/advertisement_edit.html', context)

# Function for deleting advertisement
def advertisement_delete(request, id):
    advertisement = get_object_or_404(advertisements, id=id)
    if advertisement.owner != request.user:
        raise Http404()
    advertisement.delete()
    return redirect('HomePage')

# Function for showing user's own advertisements        
def your_advertisements(request):
    advertisement={
        'advertisements': advertisements.objects.all()
    }
    return render (request, 'BariVara/your_advertisements.html',advertisement)

# Function for showing details of any particular advertisement
def advertisement_details(request,id):
    advertisement = get_object_or_404(advertisements, id=id)

    Comments=Comment.objects.filter(advertisement=advertisements.objects.get(id=id) , reply = None)
    if request.method=='POST':
        form=commentForm(request.POST or None)
        if form.is_valid():

            content=request.POST.get('content')
            print(content)
            reply_id = request.POST.get('comment_id')
            print(reply_id)
            comment_qs = None
            if reply_id:
                comment_qs = Comment.objects.get(id=reply_id)
            comment=Comment.objects.create(advertisement=advertisements.objects.get(id=id),user=request.user,content=content , reply = comment_qs)
            print(content)

            comment.save()
            return HttpResponseRedirect(advertisement.get_absolute_url())
            #form.save()
            #return redirect('HomePage')
    else:
        form=commentForm()
    context={
        'advertisement':advertisements.objects.get(id=id),
        'comments':Comments,
        'form':form,        
        }
    
    return render(request,'BariVara/advertisement_details.html',context)

# Function for filtering advertisements by budget
def Filter(request):

    query = request.GET['query']
    if query=="0":
        posts = advertisements.objects.filter(rent__gte=0)
        params = {'advertisements':posts}
        return render(request, 'BariVara/filter.html', params)
    elif query=="1":
        posts = advertisements.objects.filter(rent__lt=15000)
        params = {'advertisements':posts}
        return render(request, 'BariVara/filter.html', params)
    elif query=="2":
        posts = advertisements.objects.filter(rent__range=(15000,20000))
        params = {'advertisements':posts}
        return render(request, 'BariVara/filter.html', params)
    elif query=="3":
        posts = advertisements.objects.filter(rent__range=(20001,25000))
        params = {'advertisements':posts}
        return render(request, 'BariVara/filter.html', params)
    elif query=="4":
        posts = advertisements.objects.filter(rent__range=(25001,30000))
        params = {'advertisements':posts}
        return render(request, 'BariVara/filter.html', params)
    elif query=="5":
        posts = advertisements.objects.filter(rent__gt=30000)
        params = {'advertisements':posts}
        return render(request, 'BariVara/filter.html', params)    
        
    
# Function for searching advertisements by area
def Search(request):

    query = request.GET['query']
    posts = advertisements.objects.filter(place__icontains=query)
    params = {'advertisements':posts}
    return render(request, 'BariVara/search.html', params)

Django Project 2/DjangoProject/BariVara/templates/BariVara/Base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome to BariVara</title>
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css" integrity="sha384-3AB7yXWz4OeoZcPbieVW64vVXEwADiYyAEhwilzWsLw+9FgqpyjjStpPnpBO8o8S" crossorigin="anonymous">  
</head>
<style>
    body{
      background-color:  #2C3E50;
      background:linear-gradient(rgba(0,0,0,.3),rgba(0,0,0,.3)),url('/BariVara/static/BariVara/City5.jpg') no-repeat;
      
    }
    nav{
        width: 100%;
        background-color: #2C3E50;
        }
        nav img{
            
            width: 6%;
            height: auto;
            margin-left: 10%;
            
        }
        nav ul li {
            list-style-type: none;
            display: inline-block;
            
        }
        nav ul li a {
            text-decoration: none;
            color: white;
            padding-right: 15px;
            display: inline-block;
            border: none;
        }
        nav ul li a:hover {
            background-color: #34495E;
            color:black;
        }

        nav form button i{
            margin-right: 6%;
        }
        
</style>
<body>
    <nav class="navbar navbar-transparent " >
        <img src="{% static 'BariVara/Logo.png' %}">

        <ul>
            <li> <a href='{% url 'HomePage' %}'> Home </a></li>
            <li> <a href='{% url 'create_advertisements' %}'> Create Advertisement </a></li>
            <li> <a href='{% url 'your_advertisements' %}'> Your Advertisements </a></li>
            <li> <a href='{% url 'profile' %}'> Profile </a></li>
            
            <li> <a href="#"> About</a></li>
            <li> <a href='{% url 'logout' %}'> Log Out </a></li>
        </ul>

        

        
    </nav>
   <!-- <script type="text/javascript">
        document.getElementById("id_q").value="{{ query }}"
    </script> -->
      {% if messages %}
      {% for message in messages %}
        <div class=" alert-alert-{{message.tags}}"></div>
          {{ message }}
      {% endfor %}
  {% endif %}
      

{% block content %}

                
{% endblock content %}
  
    
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

Django Project 2/DjangoProject/BariVara/templates/BariVara/HomePage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome to BariVara</title>
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css" integrity="sha384-3AB7yXWz4OeoZcPbieVW64vVXEwADiYyAEhwilzWsLw+9FgqpyjjStpPnpBO8o8S" crossorigin="anonymous">  
</head>
<style>
    body{
      background-color:  #34495e;
      background:linear-gradient(rgba(0,0,0,.3),rgba(0,0,0,.3)),url('/BariVara/static/BariVara/City1.jpg') no-repeat;
      background-size: 100% auto;
    }
    nav{
        width: 100%;
        background-color: #2C3E50;
        }
        nav img{
            width: 6%;
            height: auto;
            
        }
        nav ul li {
            list-style-type: none;
            display: inline-block;
            
        }
        nav ul li a {
            text-decoration: none;
            color: white;
            padding-right: 15px;
            display: inline-block;
            border: none;
        }
        nav ul li a:hover {
            background-color: #34495E;
            color:black;
        }

        nav form button i{
            margin-right: 6%;
        }

        .pagination{
            margin-left:10%;
            margin-right:10%;
            margin-top: 10px;
            color: #34495e;
        }

        
</style>
<body>
  <nav class="navbar navbar-transparent " >
      <img src="{% static 'BariVara/Logo.png' %}">

      <ul>
          <li> <a href='{% url 'HomePage' %}'> Home </a></li>
          <li> <a href='{% url 'create_advertisements' %}'> Create Advertisement </a></li>
          <li> <a href='{% url 'your_advertisements' %}'> Your Advertisements </a></li>
          <li> <a href='{% url 'profile' %}'> Profile </a></li>
          
          <li> <a href="#"> About</a></li>
          <li> <a href='{% url 'logout' %}'> Log Out </a></li>
      </ul>

      

      <form method="get" action="/BariVara/search" class="form-inline">
        <input class="form-control mr-sm-2" type="search" placeholder="Search By Area"  aria-label="Search" name="query" id="query">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fas fa-search"></i><a>Search</a></button>
       </form>
       
      <form method="get" action="/BariVara/filter" class="form-inline">
        
        <select id="query" name="query">
          <option value="0">Filter by Budget</option>
          <option value="1"> Budget < 15000 Tk</option>
          <option value="2">15,000-20,000 Tk</option>
          <option value="3">20,001-25,000 Tk</option>
          <option value="4">25,001-30,000 Tk</option>
          <option value="5">30,000+ Tk</option>
          </select>
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fas fa-search"></i><a>Search</a></button>
       </form>
  </nav>
 <!-- <script type="text/javascript">
      document.getElementById("id_q").value="{{ query }}"
  </script> -->
    {% if messages %}
    {% for message in messages %}
      <div class=" alert-alert-{{message.tags}}"></div>
        {{ message }}
    {% endfor %}
{% endif %}
    


<style>
  .card{
     background-color: #2C3E50;
     color: white;
     border: 2px solid black;
     margin: 2%;
   }
</style>
<div class="container">
  <div class="row">
{% for ad in advertisement %}
<div class="col-sm-4">
   <div class="card" style="width: 16rem;">
     <div class="card-body">
       <h5 class="card-title">{{ad.place}}</h5>
       <p>House/Apartment Size: {{ad.size}} squarefeet</p>
       <p>Time Posted: {{ad.date_posted}}</p>
       <p>Rent per month: {{ad.rent}} taka</p>
       <a href='{% url 'advertisement_details' ad.id  %}' class="card-link">Full Details</a>
     </div>
   </div>
 </div>
{% endfor %}
</div> 
</div> 

<ul class="pagination">
  {% if advertisement.has_previous %}
    <li class="page-item">
      <a href="?page={{ advertisement.previous_page_number }}" class="page-link">Previous Page</a>
    </li>
  {% endif %}
  {% for ad in advertisement.paginator.page_range %}
    {% if advertisement.number == ad %}
      <li class="pafe_item active">
        <a href="?page={{ ad }}" class="page-link">{{ ad }}</a>
      </li>
    {% else %}
       <li class="pafe_item">
        <a href="?page={{ ad }}" class="page-link">{{ ad }}</a>
      </li>
    {% endif %}
  {% endfor %}

  {% if advertisement.has_next %}
      <li class="page-item">
      <a href="?page={{ advertisement.next_page_number }}" class="page-link">Next Page</a>
    </li>
  {% endif %}
              
</ul>

  
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

Django Project 2/DjangoProject/BariVara/templates/BariVara/advertisement_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome to BariVara</title>
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css" integrity="sha384-3AB7yXWz4OeoZcPbieVW64vVXEwADiYyAEhwilzWsLw+9FgqpyjjStpPnpBO8o8S" crossorigin="anonymous">  
</head>
<style>
    body{
      background-color:  #34495e;
      
    }
    nav{
        width: 100%;
        background-color: #2C3E50;
        }
        nav img{
            width: 6%;
            height: auto;
            
        }
        nav ul li {
            list-style-type: none;
            display: inline-block;
            
        }
        nav ul li a {
            text-decoration: none;
            color: white;
            padding-right: 15px;
            display: inline-block;
            border: none;
        }
        nav ul li a:hover {
            background-color: #34495E;
            color:black;
        }

        nav form button i{
            margin-right: 6%;
        }
        
</style>
<body>
    <nav class="navbar navbar-transparent " >
        <img src="{% static 'BariVara/Logo.png' %}">

        <ul>
            <li> <a href='{% url 'HomePage' %}'> Home </a></li>
            <li> <a href='{% url 'create_advertisements' %}'> Create Advertisement </a></li>
            <li> <a href='{% url 'your_advertisements' %}'> Your Advertisements </a></li>
            <li> <a href='{% url 'profile' %}'> Profile </a></li>
            
            <li> <a href="#"> About</a></li>
            <li> <a href='{% url 'logout' %}'> Log Out </a></li>
        </ul>

        

        <form method="get" action="/BariVara/search" class="form-inline">
          <input class="form-control mr-sm-2" type="search" placeholder="Search By Area"  aria-label="Search" name="query" id="query">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fas fa-search"></i><a>Search</a></button>
         </form>
         
        <form method="get" action="/BariVara/filter" class="form-inline">
          
          <select id="query" name="query">
            <option value="0">Filter by Budget</option>
            <option value="1"> Budget < 15000 Tk</option>
            <option value="2">15,000-20,000 Tk</option>
            <option value="3">20,001-25,000 Tk</option>
            <option value="4">25,001-30,000 Tk</option>
            <option value="5">30,000+ Tk</option>
            </select>
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fas fa-search"></i><a>Search</a></button>
         </form>
    </nav>
   <!-- <script type="text/javascript">
        document.getElementById("id_q").value="{{ query }}"
    </script> -->
      {% if messages %}
      {% for message in messages %}
        <div class=" alert-alert-{{message.tags}}"></div>
          {{ message }}
      {% endfor %}
  {% endif %}
      


<style>
   .container{
      border: 3px solid black;
      margin-top: 3%;
      background-color: #2c3e50;
      color: white;
   }
   .card{
      width: 50%;
      margin: 2%;
      background-color: #2c3e50;
      border: 2px solid black;

   }

   .gallery{
    margin-top: 20px;
    margin-bottom: 20px;
   }

   .img-thumbnail{
    height: 250px;
    width: 300px;
   }

</style>
   <div class="container">
         <legend class="border-bottom mb-4 text-center"><h3>House Information</h3></legend>
         <p>Location: {{ advertisement.place}}</p>
         <p>Address: {{ advertisement.address}}</p>
         <p>Size: {{ advertisement.size}} Squarefeets</p>
         <p>Number of Bedrooms: {{ advertisement.bedroom}}</p>
         <p>Number of Bathrooms:{{ advertisement.bathroom}}</p>
         <p>Rent: {{ advertisement.rent}} in Tk</p>
         <div class = "row gallery">
         {% for p in advertisement.images_set.all %}
            <div class="col-md -3">
               <img src="{{ p.image.url }}" width="50%" height="auto" alt="images" class="img-thumbnail">
            </div>
         {% endfor %}
         </div>
         <legend class="border-bottom mb-4 text-center"><h3>Owner Information</h3></legend>
         <p>Owner Name: {{ advertisement.owner}}</p>
         <p>Contact Number: {{ advertisement.number}}</p>
         {% if advertisement.owner == request.user %}
         <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'advertisement_edit' advertisement.id %}">Update</a>
         <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'advertisement_delete' advertisement.id %}">Delete</a>
         {% endif %}
         

         <br>
         <hr>

        



         <div class="main-commment-section">
          <div class="container-fluid mt-2">
            <div class="form-group row">
              <form action ="" method="POST">
                {% csrf_token %}
                {{ form.as_p}}
                <input type="submit" value="Submit" class="btn btn-outline-success">
              </form>
              
            </div>
            
           </div>
            {{ comments.count }} Comment{{ comments|pluralize }}
            {% for comment in comments %}
            <blockquote class="blockquote">
               <p class="mb-0">{{ comment.content }}</p>
               <footer class="blockquote-footer">Commented by <cite title="Source Title">{{ comment.user|capfirst }}</cite>
                 <button type ="button" name="button" class ="reply-btn btn btn-outline-success btn-sm">Reply</button>

               </footer>
             </blockquote>

          <div class="replied-comments container mt-2">

              {% for reply in comment.replies.all %}



               <blockquote class="blockquote">
               <p class="mb-0">{{ reply.content }}</p>
               <footer class="blockquote-footer">replied by <cite title="Source Title">{{ reply.user|capfirst }}</cite>
                

               </footer>
               </blockquote>
              {% endfor %}
              <div class="form-group row">



                <form action ="" method="POST">
                  {% csrf_token %}
                  <input type="hidden" name="comment_id"  value="{{ comment.id }}" >
                  {{ form.as_p}}
                  <input type="submit" value="Submit" class="btn btn-outline-success">
                </form>

                
              </div>

               
             </div>

            {% endfor %}
         </div>
    <!--<div class="row gallery">
      {% for p in advertisement.images_set.all %}
        <div class="col-md -3">
           <img src="{{ p.image.url }}" width="50%" height="auto" alt="images">
        </div>
      {% endfor %}
   </div>--> 
   </div>

                

  
    
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>